# Generated by Django 4.1 on 2022-10-16 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_perm', models.BooleanField(default=True)),
                ('new_order_perm', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='employes/')),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=50, null=True)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('official_number', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_number', models.CharField(blank=True, max_length=20, null=True)),
                ('alt_personal_number', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_number', models.CharField(blank=True, max_length=20, null=True)),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('persoanl_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('current_salary', models.IntegerField(blank=True, null=True)),
                ('current_advance', models.IntegerField(blank=True, null=True)),
                ('causal_leave', models.IntegerField(blank=True, null=True)),
                ('assigned_company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
