# Generated by Django 4.1.2 on 2022-10-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepermission',
            name='new_order_perm',
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='Cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='Complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='Exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='Initial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='Return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='Shipping',
            field=models.BooleanField(default=False),
        ),
    ]
