# Generated by Django 4.1.2 on 2022-10-22 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_company_invoice_count'),
        ('employees', '0002_remove_employeepermission_new_order_perm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='assigned_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.company'),
        ),
    ]
