# Generated by Django 4.1.2 on 2022-10-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_assigned_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='Printed',
            field=models.BooleanField(default=False),
        ),
    ]
