# Generated by Django 4.1.2 on 2022-10-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeepermission_printed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='employes'),
        ),
    ]
