# Generated by Django 4.1.2 on 2022-10-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmplpyeePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('new_order', models.IntegerField(default=0)),
                ('complete_order', models.IntegerField(default=0)),
                ('return_order', models.IntegerField(default=0)),
                ('ad_note', models.IntegerField(default=0)),
                ('rtn_note', models.IntegerField(default=0)),
                ('search', models.IntegerField(default=0)),
                ('misc', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='employees.emplpyeepoints'),
        ),
    ]
