# Generated by Django 4.1.2 on 2022-10-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_emplpyeepoints_employee_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplpyeepoints',
            name='name',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
