# Generated by Django 4.1.2 on 2022-10-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_emplpyeepoints_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmplpyeePointsHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='admin', max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('new_order', models.IntegerField(default=0)),
                ('complete_order', models.IntegerField(default=0)),
                ('return_order', models.IntegerField(default=0)),
                ('ad_note', models.IntegerField(default=0)),
                ('rtn_note', models.IntegerField(default=0)),
                ('search', models.IntegerField(default=0)),
                ('misc', models.IntegerField(default=0)),
            ],
        ),
    ]
