# Generated by Django 4.1.2 on 2022-10-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_emplpyeepointshour'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplpyeepoints',
            name='creadted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
