# Generated by Django 4.1.2 on 2022-10-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_emplpyeepoints_creadted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmplpyeePointsHour',
        ),
    ]
