# Generated by Django 4.1.2 on 2022-10-31 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_remove_employee_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplpyeepoints',
            name='name',
        ),
        migrations.AddField(
            model_name='emplpyeepoints',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
