# Generated by Django 4.1.2 on 2022-10-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_remove_emplpyeepoints_name_emplpyeepoints_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emplpyeepoints',
            old_name='creadted',
            new_name='created',
        ),
    ]
