# Generated by Django 4.1.2 on 2022-11-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_rename_creadted_emplpyeepoints_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplpyeepoints',
            name='employee',
        ),
        migrations.AddField(
            model_name='emplpyeepoints',
            name='employee',
            field=models.ManyToManyField(to='employees.employee'),
        ),
    ]
