# Generated by Django 4.1.2 on 2022-11-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='Edit',
            field=models.BooleanField(default=False),
        ),
    ]
