# Generated by Django 4.1.2 on 2022-11-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_employeepermission_edit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeepermission',
            old_name='Edit',
            new_name='edit_order',
        ),
    ]
