# Generated by Django 4.1.2 on 2022-11-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_employeepermission_print_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='employes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='mkt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='order_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='reseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='search_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='search_rtn',
            field=models.BooleanField(default=False),
        ),
    ]
