# Generated by Django 4.1 on 2022-10-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resellerorder',
            name='additional_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
