# Generated by Django 4.1 on 2022-10-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MktOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('sub_total', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='MktShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MktOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Initial', 'Initial'), ('Shipping', 'Shipping'), ('Return', 'Return'), ('Complete', 'Complete')], default='Initial', max_length=10)),
                ('qty', models.IntegerField()),
                ('product_prices', models.IntegerField(blank=True, null=True)),
                ('item_totals', models.IntegerField(blank=True, null=True)),
                ('main_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market_place_prder.mktorder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='mktorder',
            name='shop_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='market_place_prder.mktshop'),
        ),
    ]
