# Generated by Django 4.1 on 2022-10-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=20)),
                ('tittle', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='company/')),
                ('fav_logo', models.ImageField(upload_to='company/')),
                ('invoice_slug', models.CharField(max_length=300)),
                ('invoice_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
