# Generated by Django 4.1.2 on 2022-10-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='invoice_count',
            field=models.IntegerField(default=1),
        ),
    ]
