# Generated by Django 4.1 on 2022-10-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        ('products', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobille_number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('return_note', models.TextField(blank=True, null=True)),
                ('cancel_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('sub_total', models.IntegerField(blank=True, null=True)),
                ('advance', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('delivery_charge', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sites.company')),
                ('delivery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='orders.deliverymethod')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Initial', 'Initial'), ('Printed', 'Printed'), ('Shipping', 'Shipping'), ('Return', 'Return'), ('Complete', 'Complete'), ('Exchange', 'Exchange'), ('Cancel', 'Cancel')], default='Initial', max_length=10)),
                ('qty', models.IntegerField()),
                ('product_prices', models.IntegerField(blank=True, null=True)),
                ('item_totals', models.IntegerField(blank=True, null=True)),
                ('main_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.neworder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product')),
            ],
        ),
    ]
