# Generated by Django 4.1.2 on 2022-10-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neworder',
            options={'ordering': ('created_at',)},
        ),
    ]
