# Generated by Django 4.1.2 on 2022-10-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_neworder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworder',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
