# Generated by Django 4.1.2 on 2022-10-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_neworder_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworder',
            name='in_review',
            field=models.BooleanField(default=False),
        ),
    ]
