# Generated by Django 4.1 on 2022-10-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('warranty', models.CharField(max_length=20)),
                ('warranty_policy', models.TextField(blank=True, null=True)),
                ('cost_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('alert_qty', models.IntegerField()),
                ('stock_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('product_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productbrand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productcategory')),
            ],
        ),
    ]
