# Generated by Django 4.1 on 2022-10-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('products', '0003_adjuststock'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuststock',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='employees.employee'),
        ),
    ]
