# Generated by Django 4.1.2 on 2022-10-24 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.BooleanField(default=False)),
                ('mkt', models.BooleanField(default=False)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product')),
            ],
        ),
    ]
