# Generated by Django 4.1.2 on 2022-10-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_lowstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowstock',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
