# Generated by Django 4.1.2 on 2022-10-25 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_lowstock_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowstock',
            name='sku',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
