# Generated by Django 4.1.2 on 2022-10-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_lowstock_sku_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.BooleanField(default=False)),
                ('mkt', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='products.product')),
            ],
        ),
    ]
