# Generated by Django 4.1.2 on 2022-10-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_stockin'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
