# Generated by Django 4.1.2 on 2022-10-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_stockin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
