# Generated by Django 4.1.2 on 2022-10-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_current_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_stock_status',
            field=models.BooleanField(default=True),
        ),
    ]
