# Generated by Django 4.1.2 on 2022-10-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_current_stock_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='status',
        ),
    ]
