# Generated by Django 4.1.2 on 2022-10-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_stockin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
