# Generated by Django 4.1.2 on 2022-10-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_productbrand_name_alter_productcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
